name: 'Autopep'
description: 'This action checks for pep8 issues in your code and comments on the PR'
author: 'Soeren Herrmann | Pixelwelt'

on: 
  pull_request:
    branches:
      - main

jobs:
  generate_comment:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install pycodestyle
        run: pip install pycodestyle
      - name: Run pycodestyle
        id: pycodestyle
        run: |
         git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' | xargs pycodestyle --statistics > pep8_issues.txt || true
      - name: Read pycodestyle output
        id: read_pep8_issues
        run: echo "::set-output name=pep8_issues::$(cat pep8_issues.txt)"
      - name: Create comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              const pep8_issues = `\${{ steps.read_pep8_issues.outputs.pep8_issues }}`;
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Hey there after checking your code, I\'ve found the following pep8 issues. Please fix them. <br> ```' + pep8_issues + '```'
              })